"""The VPN tunnel a bundled engine may sit inside."""

from opus.engines.catalog import VPN_ENV, VPN_FIELDS, VPN_GROUP
from opus.engines.spec import EngineSpec
from opus.provision import common
from opus.settings_store import RuntimeConfig


def env(runtime: RuntimeConfig) -> dict[str, str]:
    # an unset field is not sent at all: gluetun reads an empty SERVER_REGIONS
    # as "no preference", which is right, but sending it empty alongside a
    # provider that has one is how a pin silently stops being a pin
    return {
        VPN_ENV[f.key]: value
        for f in VPN_FIELDS
        if f.key in VPN_ENV and (value := runtime.get(f"{VPN_GROUP}_{f.key}"))
    }


def seed(spec: EngineSpec) -> None:
    """gluetun's control server refuses everything until it is told who may ask.
    One read-only route is opened to nobody in particular, which is safe for the
    same reason everything else here is: the server is on the network OPUS
    shares with its engines and is published nowhere."""
    common.write_whole(
        common.config_path(spec, "tunnel", "config.toml"),
        "# Generated by OPUS.\n"
        "[[roles]]\n"
        'name = "opus"\n'
        'routes = ["GET /v1/publicip/ip"]\n'
        'auth = "none"\n',
    )
